### ISSUE TITLE
Unable to build locally on mac

### ISSUE THREAD

**Issue by Kurru** [bloomrpc/bloomrpc#373]
I'm unable to build locally on my mac - Catalina 10.15.7.

I was trying to build locally so I could get the most recent contribution (GRPC via reflection service), but it didnt build :( Any advice? (or you could do another release :D)

```
$ yarn install
yarn install v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-sortable-hoc@1.9.1" has unmet peer dependency "prop-types@^15.5.7".
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.3.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "jest > jest-cli > jest-config > jest-resolve@24.3.0" has unmet peer dependency "jest-haste-map@^24.0.0".
[4/4] 🔨  Building fresh packages...
[-/8] ⠠ waiting...
[2/8] ⠠ fsevents
[8/8] ⠐ electron
[6/8] ⠐ node-sass
warning Error running install script for optional dependency: "/Users/kurru/git/bloomrpc/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/kurru/git/bloomrpc/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@15.11.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@15.11.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@15.11.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.11.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.11.0 | darwin | x64
gypgyp info  infook
ok
gyp info it worked if it ends with ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.11.0 | darwin | x64
gyp info using node-gyp@3.8.0
gyp info using node@15.11.0 | darwin | x64
gypgyp info info spawn /usr/bin/python2
 spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gypgyp  infoinfo  spawn argsspawn args   '-f',
gyp [
 gypinfo  infospawn args    'make',
spawn argsgyp   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp  info spawn args   '-f',
gypinfo  spawn args   '-I',
gyp infoinfo  spawn argsspawn args   '/Users/kurru/git/bloomrpc/node_modules/fsevents/build/config.gypi',
   'make',
gypgyp  infoinfo  spawn argsspawn args   '-I',
   '-I',
gypgyp  infoinfo  spawn argsspawn args   '/Users/kurru/git/bloomrpc/node_modules/fsevents/build/config.gypi',
   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/addon.gypi',
gypgyp  info infospawn args    '-I',
spawn argsgyp   '-I',
 gyp infoinfo spawn args spawn args   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/addon.gypi',
   '/Users/kurru/.node-gyp/15.11.0/include/node/common.gypi',
gypgyp  infoinfo  spawn argsspawn args   '-Dlibrary=shared_library',
   '-I',
gypgyp  info spawn argsinfo   '/Users/kurru/.node-gyp/15.11.0/include/node/common.gypi',
 gypspawn args    '-Dvisibility=default',
gypinfo info  spawn argsspawn args   '-Dlibrary=shared_library',
   '-Dnode_root_dir=/Users/kurru/.node-gyp/15.11.0',
gypgyp  infoinfo  spawn argsspawn args   '-Dnode_gyp_dir=/Users/kurru/git/bloomrpc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kurru/.node-gyp/15.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kurru/git/bloomrpc/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info    '-Dvisibility=default',
spawn args   '--generator-output',
gypgyp  infoinfo  spawn argsspawn args   '-Dnode_root_dir=/Users/kurru/.node-gyp/15.11.0',
   'build',
gypgyp  info infospawn args    '-Goutput_dir=.'
gyp spawn argsinfo spawn args ]
   '-Dnode_gyp_dir=/Users/kurru/git/bloomrpc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kurru/.node-gyp/15.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kurru/git/bloomrpc/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/kurru/git/bloomrpc/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/usr/local/Cellar/node/15.11.0/bin/node\" \"/Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/kurru/git/bloomrpc/node_modules/fsevents
gyp ERR! node -v v15.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/kurru/git/bloomrpc/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/usr/local/Cellar/node/15.11.0/bin/node\" \"/Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/kurru/git/bloomrpc/node_modules/fsevents
gyp ERR! node -v v15.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/15.11.0/bin/node /Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64/fse.node --module_name=fse --module_path=/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64 --napi_version=7 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kurru/git/bloomrpc/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/15.11.0/bin/node\" \"/Users/kurru/git/bloomrpc/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/kurru/git/bloomrpc/node_modules/fsevents
node-pre-gyp ERR! node -v v15.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/15.11.0/bin/node /Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js[-/8] ⠁ waiting...                                                                                                        [2/8] ⠁ fsevents                                                                                                          [8/8] ⠁ electron
[6/8] ⠁ node-sass
error /Users/kurru/git/bloomrpc/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/kurru/git/bloomrpc/node_modules/node-sass
Output:
Building: /usr/local/Cellar/node/15.11.0/bin/node /Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/15.11.0/bin/node',
gyp verb cli   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.11.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 15.11.0
gyp verb command install [ '15.11.0' ]
gyp verb install input version string "15.11.0"
gyp verb install installing version: 15.11.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.11.0
gyp verb build dir attempting to create "build" dir: /Users/kurru/git/bloomrpc/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/kurru/git/bloomrpc/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/kurru/git/bloomrpc/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/kurru/git/bloomrpc/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/kurru/git/bloomrpc/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kurru/git/bloomrpc/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kurru/git/bloomrpc/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kurru/.node-gyp/15.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kurru/.node-gyp/15.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/kurru/git/bloomrpc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kurru/.node-gyp/15.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kurru/git/bloomrpc/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/kurru/git/bloomrpc/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/15.11.0/bin/node" "/Users/kurru/git/bloomrpc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/kurru/git/bloomrpc/node_modules/node-sass
gyp ERR! node -v v15.11.0
```

**Comment by Kurru** [comment]
Update, after [running instructions found online](https://medium.com/@mrjohnkilonzi/how-to-resolve-no-xcode-or-clt-version-detected-d0cf2b10a750), I have a new mysterious failure. 

```
warning Error running install script for optional dependency: "/Users/kurru/git/bloomrpc/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/kurru/git/bloomrpc/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@15.11.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/kurru/git/bloomrpc/node_modules/fsevents/lib/binding/Release/node-v88-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@15.11.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v88-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@15.11.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
```
[pastebin](https://pastebin.com/cm9hQrAU)
