### ISSUE TITLE
Can't build it on Ubuntu20.04

### ISSUE THREAD

**Issue by jinyunshaobing** [bloomrpc/bloomrpc#449]
I can not build it locally on my Ubuntu20.04,It seems that `https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-x64.zip` is an invalid address?
```
• electron-builder  version=22.3.2 os=5.15.0-43-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=grpc@1.24.11, grpc@1.24.7 platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=7.1.11 appOutDir=release/linux-unpacked
  ⨯ Get https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-x64.zip: dial tcp 20.205.243.166:443: connect: connection timed out
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:158
github.com/develar/app-builder/pkg/download.(*Downloader).follow
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:186
github.com/develar/app-builder/pkg/download.(*Downloader).Download
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:80
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357  
  ⨯ /home/lizhijie/Software/bloomrpc/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                Error: /home/lizhijie/Software/bloomrpc/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                    at ChildProcess.childProcess.once.code (/home/lizhijie/Software/bloomrpc/node_modules/app-builder-lib/node_modules/builder-util/src/util.ts:239:14)
                                                                                                                                                    at Object.onceWrapper (events.js:286:20)
                                                                                                                                                    at ChildProcess.emit (events.js:198:13)
                                                                                                                                                    at maybeClose (internal/child_process.js:982:16)
                                                                                                                                                    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bloomrpc@1.5.3 package: `yarn build && electron-builder build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bloomrpc@1.5.3 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lizhijie/.npm/_logs/2022-09-14T08_30_49_692Z-debug.log

```

**Comment by allan2** [comment]
@jinyunshaobing are you still experiencing this error?

The link you posted seems to be working.
